# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\USER\PycharmProjects\data_sagd\SAGD_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(436, 234)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_year = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_year.setGeometry(QtCore.QRect(90, 70, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_year.setFont(font)
        self.comboBox_year.setObjectName("comboBox_year")
        self.pushButton_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_file.setGeometry(QtCore.QRect(20, 20, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_file.setFont(font)
        self.pushButton_file.setObjectName("pushButton_file")
        self.comboBox_param = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_param.setGeometry(QtCore.QRect(90, 110, 321, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_param.setFont(font)
        self.comboBox_param.setObjectName("comboBox_param")
        self.pushButton_calc = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calc.setGeometry(QtCore.QRect(20, 150, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_calc.setFont(font)
        self.pushButton_calc.setObjectName("pushButton_calc")
        self.label_year = QtWidgets.QLabel(self.centralwidget)
        self.label_year.setGeometry(QtCore.QRect(20, 70, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_year.setFont(font)
        self.label_year.setObjectName("label_year")
        self.label_param = QtWidgets.QLabel(self.centralwidget)
        self.label_param.setGeometry(QtCore.QRect(20, 110, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_param.setFont(font)
        self.label_param.setObjectName("label_param")
        self.lineEdit_file = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_file.setGeometry(QtCore.QRect(150, 24, 261, 31))
        self.lineEdit_file.setObjectName("lineEdit_file")
        self.label_between = QtWidgets.QLabel(self.centralwidget)
        self.label_between.setGeometry(QtCore.QRect(360, 160, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_between.setFont(font)
        self.label_between.setText("")
        self.label_between.setObjectName("label_between")
        self.checkBox_all_years = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_all_years.setGeometry(QtCore.QRect(290, 70, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_all_years.setFont(font)
        self.checkBox_all_years.setObjectName("checkBox_all_years")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 436, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DataSAGD"))
        self.pushButton_file.setText(_translate("MainWindow", "Выбрать файл"))
        self.pushButton_calc.setText(_translate("MainWindow", "Рассчитать"))
        self.label_year.setText(_translate("MainWindow", "Год:"))
        self.label_param.setText(_translate("MainWindow", "Параметр:"))
        self.checkBox_all_years.setText(_translate("MainWindow", "за весь период"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
